import type { Metadata } from "next";
import "./globals.css";
import MainContainer from "@/components/Containers/MainContainer";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MainContainer>
        <Header />
        {children}
        <Footer />
      </MainContainer>
    </html>
  );
}
